### ISSUE TITLE
Waymo → nuScenes

### ISSUE THREAD

**Issue by AlphaPlusTT** [zhuoxiao-chen/ReDB-DA-3Ddet#1]
The impact of REDB for Waymo adapt to nuScenes is significantly limited, why？

**Comment by zhuoxiao-chen** [comment]
Thanks for your question. 

1. **Challenging Dataset**: The nuScene dataset inherently poses significant challenges, resulting in the model (SECOND) achieving fully-supervised training results of only 18.92 (pedestrian) and 11.73 (cyclist) 3D mAP.
2. **Significant domain gap**: There exist large domain gaps between Waymo and nuScene, such as very different object densities and beam numbers, which introduces a level of complexity when attempting to adapt to nuScene.

The coexistence of these two factors introduces error accumulation in pseudo-labelling. In the case of ST3D++, which focuses on adapting one model for a single class, the 3D mAP results are just 8.91 (pedestrian) and 4.84 (cyclist). However, when we transition to a more realistic scenario, training all three classes simultaneously while adapting at once, the performance of ST3D++ drops significantly to 1.58 (pedestrian) and 3.74 (cyclist).

Regards, 
Zhuoxiao (Ivan) Chen
